version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sw-backend
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    container_name: sw-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8080
    ports:
      - "6969:80"
